name: Sarko Meené
favicon: null
layout_spectrum: 0.48143
typography_spectrum: 0.2462278821039945
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b4b4b4'
    - '#1c1c1c'
    - '#3d3d3d'
    - '#939393'
    - '#7b7b7b'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.32341718836687505
  rhythmicContrast: 0.5
purpose: []
